version: 2
updates:
  - package-ecosystem: "bundler"
    directories:
      - "/"
      - "/dependabot-investigation"
      - "/dependabot-investigation/dependabot-investigation"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"